---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: neon-role
spec:
  encryptedData:
    password: AgBV2liQWgvS2iEozZCOQowA3ymhxhKgF/rOhfKei17jfiSQdhXJjihtXzItfA2XrPxk1eBxjAHy7tc60amM8Uf0mQttaOiZLNbOGZc+woY7p2bhvqc0judMMZ1Bz4CHuR7EgvNtK/bJ6RHfXSCGwCfrJRperdjExlM5YUBLaMGwkzQZVBoJEChyKYY8LYVFut29wK7j1l2elgF2O4WOfWw1qY9NNyl35Knvn4s+vIW4muUrjdenZer65gF6EeeH3xsMH0wRU/qX3mWbHM1oq3mrvX4H3SGuq2Yk5UiYXKRGZJXnsEVU35/U5GjkqiJOgTsC8ACeq4wqHS0SpJndVh10m/PrpRNRakAH1ZnmEmmv4tkCr41+BFI0RM9/rwhGrCyUzcoZle3gSZZfavD4XywjDlgIygS3ZAR4j+x2e3Cg4w+BnwGB/lMUJZUReOQqJ5CTqbRpIYlfR5PSh9QuCJS83Y69k9dFWdqlxPnHLnVmGwod0h8onMYlWlIqwXaZE/uY1fC0T3LD5qcb/V5AAwFZlfaC1mKGHdOBcfsHbTuxRk6CIWbpoiS48DSqDlX/voYBL+PZnapsiolRAq5ru6fFznQwuUKaNlMbkqiGybkxO2WBab5H+cNluTzuR24Q/Q8hzpPjHVDESNYQpzMNUTkJ16RPD+Phe5w7ihpzHOCNCRmeHlon0OCa8vFfiriVxkt0bgaRcv+oj3somcU=
    username: AgAY5ollVMT1HO0T6B4LANU4aSIsZ/AoBCNEp8zQh36vBblIJ2KOPOx+SinAb2dmGndQNEOdG3Ip/CnkLvM9nxN3gqL6cjl7KzhLaXXVqXksBwfEyYQZ94h4fAMxfB1msZkDAjOICx4DHgPwPZ0WNt2gCpkzoinx6Jq+Om4nblbRL8iL1AXGgi4VDD1PO0GQ7Q8eu3WcMzPxqav3FDb8tF64IZ1C7qRGjqu3u4SHSCb3udVlF2DYSg6xJ5tWAjIOIJIncSXCU9x2MjaEm9QFAOXq2GaGRPra4RdE8jGvPwF87QScE2jPahTJsKDR4+0KAbixjylPLb2KY5pzylyzyK2wO5voQSnuheSY0qn6xpG3VbENySbccq2GKQDaDBkZjTO8/W59dKYDMcqseXjyYQu0tfZRKexChBwovZsLKZ5/n28/bb7BX5Rcu6bcyW8fW18M49Xgto7bpiVfd0kiAdLyd7xQ+IZVVWH5KBEz6/HNMNMxk6QwYUN1h/dpVyJp7yBQdhW0fIgsx04nfMv9lqNCha5qcB3zYEyWyI2sd7hGgLaXM/51aur0w+r36fKDX3ubrlpqT6cpAeIL/HQuUH5bX9GxW/C29A9NdClpPBJalWfujW3lzC/v15vsfNZ2N+TMN2al2SRUpOBHWt2ksz9EcuGtvpMsC8nhA/c920tjGT1Xqyv8sutmbaBpi10OzX7PcCGO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: neon-role
